using Newtonsoft.Json;

namespace Unbiased.Playwright.Domain.DTOs
{
    /// <summary>
    /// Represents the response from the DALL-E API for image generation.
    /// </summary>
    public class DalleImageGenerateResponseDto
    {
        /// <summary>
        /// The timestamp when the image was created.
        /// </summary>
        [JsonProperty("created")]
        public long Created { get; set; }

        /// <summary>
        /// The array of image data generated by the API.
        /// </summary>
        [JsonProperty("data")]
        public ImageData[] Data { get; set; }

        /// <summary>
        /// Represents a single image data entity.
        /// </summary>
        public class ImageData
        {
            /// <summary>
            /// The revised prompt used to generate the image.
            /// </summary>
            [JsonProperty("revised_prompt")]
            public string RevisedPrompt { get; set; }

            /// <summary>
            /// The URL of the generated image.
            /// </summary>
            [JsonProperty("url")]
            public string Url { get; set; }
        }
    }
}
