namespace Unbiased.News.Domain.DTOs
{
    /// <summary>
    /// Data transfer object for news system statistics information.
    /// </summary>
    public class StatisticsDto
    {
        /// <summary>
        /// The total number of news scans performed by the system.
        /// </summary>
        public int ScanCount { get; set; }
        
        /// <summary>
        /// The total count of news items generated by the system.
        /// </summary>
        public int GeneratedCount { get; set; }
        
        /// <summary>
        /// The average bias score across all generated news items.
        /// </summary>
        public double AverageBiasScore { get; set; }
    }
}
